spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
  application:
    name: brain
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  http:
    converters:
      preferred-json-mapper: jackson2
  jackson:
    # 这一行相当于你的 mapper.setVisibility(...)
    visibility:
      field: any          # 对应 PropertyAccessor.FIELD, Visibility.ANY
      getter: none        # 对应 PropertyAccessor.GETTER, Visibility.NONE
      is-getter: none     # 对应 PropertyAccessor.IS_GETTER, Visibility.NONE
    write:
      date-timestamps: false
    find-and-add-modules: true
lombok:
  getter:
    noIsPrefix: true